### PR TITLE
jack_wait: return exit code failure on timeout

### PR DESCRIPTION
**Pull request by twischer-adit**
Signed-off-by: Timo Wischer <twischer@de.adit-jv.com>

### CODE REVIEW

**Comment by falkTX** [comment]
the idea is great, but please keep the existing indentation in place.

**Comment by twischer-adit** [comment]
@falkTX
I replaced it with taps like the rest of the source file.
Should I really leave it at is it?
This is the only position in this file where spaces were used to indent.

Alternatively I could create a separate commit for it...

**Comment by falkTX** [comment]
A separate commit is better yes. thanks.

**Comment by twischer-adit** [comment]
Done

**Comment by falkTX** [comment]
Looks good now, thank you!

**Pull request merged**
