### PR TITLE
Add a Proxy driver

### PR DESCRIPTION
**Pull request by sdrik**

### CODE REVIEW

**Comment by adiknoth** [comment]
Did you talk to sletz about this? I don't recall any discussion on jack-devel@ about this. Looks interesting.

**Comment by sdrik** [comment]
I posted it on jack-devel@ under the topic "Multi-user desktop integration" back in november, but it didn't attract a lot of comments.

**Comment by sletz** [comment]
Can you possibly resynch your branch with latest jack2 state?


Le 15 avr. 2015 � 22:33, C�dric Schieli <notifications@github.com> a �crit :

**Comment by sdrik** [comment]
Yes. That's on my todo list. But I can't promise it will happen before a few weeks from now.

**Comment by sdrik** [comment]
I've just rebased my pull/proxydriver-v1 branch on top of current master.

**Comment by sletz** [comment]
Trying yo compile your branch on OSXn but "jack_group2gid" is missing at link time. It the "gid.c" file supposed to be added in the project? Or should the "jack_group2gid" function be made Linux only?

**Comment by sdrik** [comment]
The jack_group2gid is not Linux-specific, only its use within JackPosixSemaphore is. So yes, it should be added into the macosx project. I've only addressed the waf build so far.

**Comment by sletz** [comment]
Merger, but I don't see this "jack_group2gid" related code in the final merge...

**Comment by sdrik** [comment]
jack_group2gid is part of the #77 pull request and is not mandatory for the
proxy driver.
Thanks for the merge.

2015-04-28 2:43 GMT+02:00 Stéphane Letz <notifications@github.com>:

**Pull request merged**
