### PR TITLE
Enhance promiscuous mode

### PR DESCRIPTION
**Pull request by sdrik**

### CODE REVIEW

**Comment by adiknoth** [comment]
Was there a discussion about this pull request?

I definitely like the first patch about audio reservation. I'm less sure about the 2nd, I feel the implementation could be easier.

**Comment by adiknoth** [comment]
I've merged the first commit.

**Comment by adiknoth** [comment]
This PR no longer cleanly applies. If you still care about it, please rebase and ping the thread so that we can merge promptly.

**Comment by sdrik** [comment]
The PR has been rebased onto current master.

**Comment by falkTX** [comment]
Please note that latest git no longer uses JackPosixSemaphore.cpp/h in linux builds.

**Comment by sdrik** [comment]
Thanks for the heads up. I'll look into this asap.

**Comment by falkTX** [comment]
I don't think some of that code will compile under OSX, specially sysconf stuff...
Since you use a macro test for __linux__ under the semaphore code, I suggest adding the same __linux__ check in gid.c

**Comment by sdrik** [comment]
Closing this one. See #257 for a reworked version.

**Pull request closed without merging**
