### PR TITLE
v1.9.14

### PR DESCRIPTION
**Pull request by falkTX**

### CODE REVIEW

**Comment by schnitzeltony** [comment]
With packager's hat on: Will you tag this as 'official release?

**Comment by falkTX** [comment]
soon...

did you test the release? that would speed up things.
just waiting for confirmation on @wtay that the dbus fix is reliable.

**Comment by schnitzeltony** [comment]
Ahh - ok - thanks

Up to now I just build tested. Can do a run test tonight - and drop a note.

**Comment by wtay** [comment]
Hi, I can confirm that the dbus patched version works. W_

**Comment by schnitzeltony** [comment]
I know it is not a systematic test but I did run it for some ours with things I use to do usually and no regressions pooped up.

**Pull request merged**
