### PR TITLE
Set ToS on Netjack2 packets

### PR DESCRIPTION
**Pull request by jmendeth**
Set the ToS/DS field on the packets sent over the network (the code was commented out for some reason).

This should make most network hops prioritize Netjack2 packets over other kinds of traffic.

### CODE REVIEW

**Comment by jmendeth** [comment]
Note: the value of `46` means Expedited Forwarding (or for older equipment, critical priority), which is common to use in realtime voice / sound apps.

**Comment by falkTX** [comment]
There must be a reason why the code was disabled before. any ideas on why?

**Comment by sletz** [comment]
Because it has never shown any kind of improvement I guess.

**Comment by falkTX** [comment]
Then I guess it is safe to merge.
We just be on the watch for future bug reports.

**Pull request merged**
