### PR TITLE
Fix ringbuffer thread safety on ARM. Fix #715 #388

### LINKED ISSUE #715: Thread safety of jack ringbuffer on ARM
## Describe the bug

This is a follow up to #388.

I am able to consistently reproduce an overbound read problem on a Raspberry Pi 4 using the test program in https://github.com/jackaudio/jack2/issues/388#issuecomment-453283106. Here is a sample output

```
...
---------------- 418756/1000000 ----------------
---------------- 418757/1000000 ----------------
message (0) != expected (82)
```

It happens almost deterministically for 1000000 iterations, but the exact timing is random. This program always terminates correctly on x86 and it only occurs on ARM.

The basic problem is that the write pointer is advanced before data is written completely. This is probably due to ARM's relaxed memory ordering. I am not sure about Apple Silicon, but it might also suffer from the same issue. A memory barrier here is not optional.

I will reproduce a cleaned up test program here:

```c
//          Copyright Jean Pierre Cimalando 2018.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE or copy at
//          http://www.boost.org/LICENSE_1_0.txt)

// g++ -O2 -o test_case test_case.cc -ljack -lpthread

#include <jack/ringbuffer.h>
#include <memory>
#include <thread>
#include <stdio.h>
#include <stdlib.h>
#include <sched.h>

jack_ringbuffer_t *ring_buffer;
size_t capacity = 1024;
size_t message_count = 100;
size_t message_size = 100;

void thread1()
{
  jack_ringbuffer_t *rb = ::ring_buffer;
  const size_t message_size = ::message_size;
  const size_t message_count = ::message_count;
  std::unique_ptr<uint8_t[]> message_buffer(new uint8_t[message_size]);

  for (size_t i = 0; i < message_count;) {
    *(size_t *)message_buffer.get() = i;

    size_t can_write=jack_ringbuffer_write_space(rb);
    size_t count=0;
    if (can_write>=message_size) {
      count = jack_ringbuffer_write(rb, (const char *)message_buffer.get(), message_size);
    }
    if (count == message_size)
      ++i;
    else
      sched_yield();
  }
}

void thread2()
{
  jack_ringbuffer_t *rb = ::ring_buffer;
  const size_t message_size = ::message_size;
  const size_t message_count = ::message_count;
  std::unique_ptr<uint8_t[]> message_buffer(new uint8_t[message_size]);

  for (size_t i = 0; i < message_count;) {
    size_t can_read=jack_ringbuffer_read_space(rb);
    size_t count=0;
    if (can_read>=message_size) {
      count = jack_ringbuffer_read(rb, (char *)message_buffer.get(), message_size);
    }

    if (count == message_size) {
      size_t msg = *(size_t *)message_buffer.get();
      if (msg != i) {
        printf("message (%zu) != expected (%zu)\n", msg, i);
        exit(1);
      }
      ++i;
    }
  }
}

int main()
{
  size_t ntimes = 1000000;
  for (size_t i = 0; i < ntimes; ++i)
  {
    printf("---------------- %4zu/%4zu ----------------\n", i + 1, ntimes);
    jack_ringbuffer_t *rb = ::ring_buffer = jack_ringbuffer_create(::capacity);
    std::thread t1(thread1);
    std::thread t2(thread2);
    t1.join();
    t2.join();
    ::ring_buffer = nullptr;
    delete rb;
  }
  printf("-------------------------------------------\n");
  printf("success!\n");

  return 0;
}
```

## Environment

* **JACK Version:** 1.9.12 (`ringbuffer.c` hasn't been touched for 10 years)
* **Operating System:** Linux (Raspberry Pi OS)
* **Installation:** package manager

## Steps To Reproduce

```bash
$ g++ -O2 -o test_case test_case.cc -ljack -lpthread
$ ./test_case
```

Wait until it fails.

### Expected vs. actual behavior

No overbound read should happen and the test program should always exit with a success on ARM.

### PR DESCRIPTION
**Pull request by Krasjet**
This patch addresses the thread safety problem of `jack_ringbuffer_t`
mentioned in #715 and #388. The overbound read bug caused by this problem
is impossible to reproduce on x86 due to its strong memory ordering, but
it is a problem on ARM and other weakly ordered architectures.

Basically, the main problem is that, on a weakly ordered architecture,
it is possible that the pointer increment after `memcpy` becomes visible
to the other thread before `memcpy` finishes:

	memcpy (&(rb->buf[rb->write_ptr]), src, n1);
	// vvv can be visible to reading thread before memcpy finishes
	rb->write_ptr = (rb->write_ptr + n1) & rb->size_mask;

If this happens, the other thread can read the remaining garbage values
in `rb->buf` due to be overwritten by the unfinished `memcpy`.

To fix this, an explicit pair of [release/acquire memory fences][1] is
used to ensure the copy on the other thread *happens after* the `memcpy`
finishes so no garbage values can be read.

[1]: https://preshing.com/20130922/acquire-and-release-fences/

### CODE REVIEW

**Comment by falkTX** [comment]
Nice one.
Though since this is C code, we can simply change it to use C11 and use the new functions dedicated to this? Any reason to not go that route?

**Comment by Krasjet** [comment]
The main problem is that atomics is an optional component in C11. Notably, MSVC [does not support it](https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/#whats-not), even though it is available as a C++ standard library. So to use the portable memory fence, we have to call a C++ function or convert jack_ringbuffer to C++, etc. Since the jack ringbuffer implementation is used elsewhere (pipewire, jack1, etc.), I think the best option is to keep it a self-contained C implementation.

**Comment by Krasjet** [comment]
Do you think we should remove the `volatile` qualifier for `write_ptr` and `read_ptr` as well? The `__atomic_thread_fence` intrinsic should already prevent compiler reordering (I'll have to add a compiler barrier for x86 MSVC though).

**Comment by 0EVSG** [comment]
As I understand, the only case where `volatile` would matter in presence of `__atomic_thread_fence` is when being used from a signal handler (in the same thread). Not very likely, and the code doesn't seem robust in that sense anyway, but maybe we should keep them just in case.

FWIW, I did a short review of the changes and they look good to me, I'm not that experienced with memory barriers though. And I also checked that the thread fences are actually used on FreeBSD / Clang. So this is a go from me.

**Comment by Krasjet** [comment]
There is actually a small overhead for using `volatile`. For example, you can see in the assembly generated [by gcc](https://godbolt.org/z/n8PT9fq1v) and [MSVC](https://godbolt.org/z/dseY54bs9) for `jack_ringbuffer_write` that every access to `write_ptr` issues a `mov` instruction when `volatile` is present
```asm
mov     ..., QWORD PTR [rbp+8]
```
but the write pointer is never going to be updated by the reading thread and it can be cached if we remove `volatile`.

The [`volatile` keyword in MSVC](https://docs.microsoft.com/en-us/cpp/cpp/volatile-cpp?view=msvc-170#end-of-iso-conformant) also has some non-portable semantics that enforces the release-acquire ordering when `/volatile:ms` is present. It's only enabled by default on x86, not ARM, but when the flag is present when compiling for ARM, the compiler also generates unnecessary `ldar` and `stlr` instructions that serves the same purpose as memory fences.

**Comment by Krasjet** [comment]
I just checked that removing the `volatile` keyword in C doesn't seem to break the ABI, so I'll include the change as well.

An additional optimization for read/write space calculation is also added based on the discussion for zix ringbuffer [here](https://github.com/drobilla/zix/pull/1#issuecomment-1212687196).

**Comment by Krasjet** [comment]
The changes should be ideally cherry-picked to jack1 as well. When it's ready.

**Comment by elan** [comment]
I assume this will be merged at some point? 😅

**Comment by falkTX** [comment]
yes of course. sorry for slow / little activity, lots of stuff happening at the same time lately.
there is a new incompatibility with new macOS too, still to be fixed.
these 2 things warrant a new release, maybe in december.

**Comment by Krasjet** [comment]
Apparently the CI is down again for FreeBSD. Not a problem with the code.

**Comment by 0EVSG** [comment]
FreeBSD CI should be fixed now on the develop branch.

**Pull request merged**
