### PR TITLE
Correct typos in JackNetTool.cpp

### PR DESCRIPTION
**Pull request by jmendeth**
Missing parentheses in `JackNetTool.cpp`, see patch.

### CODE REVIEW

**Comment by joshdekock** [comment]
@sletz Is it actually meant to be `((fNPorts * fCompressedMaxSizeByte) + CDO)` or will this actually fix a typo?

**Comment by jmendeth** [comment]
I'm confident this was a typo. `CDO` are the 2 bytes for the length. Since every port has these 2 bytes before the data, it only makes sense to do `fNPorts * (fCompressedMaxSizeByte + CDO)`.

That's why, if you look at the rest of the code, `CDO` is only used in `(fCompressedMaxSizeByte + CDO)`.

**Comment by sletz** [comment]
Robin Gareus wrote the code.

Le 11 mars 2016 � 13:13, Xavier Mendez <notifications@github.com> a �crit :

**Comment by adiknoth** [comment]
@x42 Hey Robin!

If you still remember anything from that code, it should be easy for you to click the merge button (or reject if you know the original code is correct).

**Comment by adiknoth** [comment]
I assume @jmendeth has looked more carefully into this than anyone else by now. Merging this.

**Pull request merged**
