### PR TITLE
[WIP] Prepare for tool submodule

### PR DESCRIPTION
**Pull request by mseeber**
Seperates tools from example clients
- Windows and OSX build was not tested
- Please test before merging
- please review the top dir wscript changes

### CODE REVIEW

**Comment by adiknoth** [comment]
What's the latest here? Didn't somebody recently rewrite the build system?

**Comment by mseeber** [comment]
I flagged this as work in progress. I obviously need to rebase on some changes and clearly explain the purpose of this PR.

**Comment by adiknoth** [comment]
Do we still want to do this? A couple of merge conflicts, but you already said this back in 2015. ;)

There was someone else on jack-devel a couple of weeks (months?) ago who was discussing using submodules. Looks like this is the direction we're going.

If you still care about this PR, just update and ping the thread, so that I can merge.

**Comment by mseeber** [comment]
I'd close this, as I currently do not have the time to get myself into this again. If anyone wants to pick this up, feel free to do so.

**Pull request closed without merging**
