### PR TITLE
AVTP Backend - second try

### PR DESCRIPTION
**Pull request by chris-kuhr**
now with develop branch as codebase

### CODE REVIEW

**Comment by 7890** [comment]
That's a lot of files!
A quick look shows that somehow things are added that are already in develop branch. For instance taking the first file in the commit, `.ci/install-deps.sh` -> in the PR, it seems like the same but every line is a '+'. this needs a closer look.
I think we must try to split up to smaller chunks for better overview. Best would be to have portions that can be merged with no risk first (eg. whitespace changes as a simple example).

**Comment by 7890** [comment]
@chris-kuhr if we can add that backend to jack it will be great! Please be aware that it will take time. PR that do a lot of changes are real beasts to tackle.

**Comment by falkTX** [comment]
Please create a proper patch, this is really not acceptable, I am sorry.
I am not sure what you did with your local repo, but consider creating a local patch and recreating the changes in a new clone.
As it stands right now, it is really unacceptable.

**Comment by chris-kuhr** [comment]
hm. that's odd. I have only added the subdirectory linux/avb, the .gitmodules file and I added 20 lines to wscript. I merely add something rather then modifying a lot.

I made a fresh clone of the jack2/develop branch and merged it. what have done wrong? I don't see it right now...

**Comment by falkTX** [comment]
Just take a look at the changes tab here in github.
Though not sure if possible, your browser might get stuck as it is really a lot of unneeded changes there.
Somehow you managed to get more changes compared to the last PR.

Please consider creating a local patch and recreating/applying the changes in a new clone.
Don't just merge all your commits, but a single one with a clean patch file.

**Comment by 7890** [comment]
I'm picking out another example:
https://github.com/jackaudio/jack2/pull/451/commits/3107ef4eb3a668609ce05c07651172b4f328c5e9
-> for a new feature: it would be wishful to have it in one go, with verbose commit message.
We have to be picky to some degree and it feels odd but it's the only way to go.

Here's what I'd try to do:
-Checkout fresh jack develop
-Meld/merge your working AVTP branch with jack develop (this might need manual work)
-Identify groups of related changes and commit them with verbose commit message
-Commit dependencies in the order they are needed ("build up")

Thanks for caring about JACK!

**Comment by chris-kuhr** [comment]
Wow! I am amazed how uninterested you are in solving this problem. When I find the time, I will have another look into it. But that won't be any time soon. Anyone interested can access my repository...

**Comment by falkTX** [comment]
It is not our job to clean up every single PR that comes our way.
Often they are well made that it is not an issue, but here it is just awful.
I am sorry, but it is just how it looks. Compared to what I have seen before so far, this is one of the worst...

I am going on holiday tomorrow, won't be with laptop or online much, so no time for me to try to sort this out.
In 2-3 weeks I will have time again and can see if I can sort out the mess.
Hopefully merging things into a branch can work out and we are able to take out a clean diff.

**Comment by 7890** [comment]
@chris-kuhr the interest is there, certainly from my side.. 
@falkTX we should possibly write up some guidelines anytime soon on the format and style of pull requests for them to be in shape as desired

**Comment by falkTX** [comment]
> @falkTX we should possibly write up some guidelines anytime soon on the format and style of pull requests for them to be in shape as desired

I am not sure if that is needed. I am not picky on PRs, as long as they are mergeable.
I did already in the past merge some stuff where I had to fix afterwards.
This one though, hopefully you agree, is not one of those...

**Comment by chris-kuhr** [comment]
Yeah, but bedside manners do help...

**Comment by 7890** [comment]
@falkTX from what I can see I agree with you - it's a hard one to overview and seemingly introduces unrelated changes .. 
Let's be clear that doesn't tell anything about the code quality, it's about the process of adding an addition very transparently and cleanly to the existing code base and the current PR won't let us do that.
The work is not lost. It's doable.
@falkTX  Enjoy the hollydays!

**Comment by falkTX** [comment]
> Yeah, but bedside manners do help...

I am not complaining about you as person or the code written here, just the way that the PR is made.
I actually don't know how this is even possible in the first place..

Anyway, it is still possible to merge, we (from jack project) just have to get our hands dirty and clean up things.
But there is a review process still to go through, right now it is impossible to do so.

**Comment by ahellquist** [comment]
I am super interested as a non coding Jack user with more than one AVB
device that I would like to use in an easy way. Really appreciate the
effort. Seems like something strange had happened here with your PR.

Thanks anyway
/Anders

**Comment by vikwil** [comment]
@chris-kuhr Really interesting, it would be great to get a standardized network interface for Jack.

About the PR. I recommend that you squash all commits in your fork into one and rebase it on upstream/develop. [Like this](https://gist.github.com/vikwil/52e2aa2393a18b499919dd3d2bccab29). There are still some cleaning up to do like not committing temporary files with ~ at the end.

**Pull request closed without merging**
