### PR TITLE
If pthread_setschedparam() in JackPosixThread::AcquireRealTimeImp() f…

### PR DESCRIPTION
**Pull request by imaami**
…ails

try again with the SCHED_RESET_ON_FORK flag before giving up. This fixes
PulseAudio's JACK modules not being granted real-time scheduling.

Signed-off-by: Juuso Alasuutari <juuso.alasuutari@gmail.com>

### CODE REVIEW

**Comment by falkTX** [comment]
Makes sense, and why not.
I will merge after confirming CI builds still succeed.
Thanks.

**Comment by imaami** [comment]
> Makes sense, and why not.
> I will merge after confirming CI builds still succeed.
> Thanks.

That was fast. :)

For reference, here's a relevant PulseAudio issue thread: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/issues/292

**Comment by CarloWood** [comment]
I'm still getting the same error :(.
Using archlinux with

>pacman -Q | egrep '(pulse|jack|realtime)'
jack-stdio 1.5-2
jack2 1.9.14-1
jack_utils 0.0.1-1
libpulse 13.0-3
pulseaudio 13.0-3
pulseaudio-jack 13.0-3
qjackctl 0.6.2-1
realtime-privileges 2-1

>groups
root realtime audio wheel carlo

>ulimit -r
98

>cat ~/.pulse/daemon.conf
.include /etc/pulse/daemon.conf
rlimit-rttime = -1
realtime-priority = 99

>cat ~/.config/jack/conf.xml
<?xml version="1.0"?>


<jack>
 <engine>
  <option name="driver">alsa</option>
  <option name="realtime">true</option>
  <option name="realtime-priority">20</option>
  <option name="verbose">false</option>
  <option name="sync">false</option>
  <option name="self-connect-mode">a</option>
 </engine>
 <drivers>
  <driver name="dummy">
  </driver>
  <driver name="netone">
  </driver>
  <driver name="alsarawmidi">
  </driver>
  <driver name="net">
  </driver>
  <driver name="proxy">
  </driver>
  <driver name="loopback">
  </driver>
  <driver name="firewire">
  </driver>
  <driver name="alsa">
   <option name="device">hw:Generic,0</option>
   <option name="capture">hw:Generic,0</option>
   <option name="playback">hw:Generic,0</option>
   <option name="rate">48000</option>
   <option name="period">256</option>
   <option name="nperiods">2</option>
   <option name="hwmeter">false</option>
   <option name="duplex">true</option>
   <option name="softmode">false</option>
   <option name="monitor">false</option>
   <option name="dither">n</option>
   <option name="inchannels">2</option>
   <option name="outchannels">2</option>
   <option name="shorts">false</option>
  </driver>
 </drivers>
 <internals>
  <internal name="netmanager">
  </internal>
  <internal name="profiler">
  </internal>
  <internal name="netadapter">
  </internal>
  <internal name="audioadapter">
  </internal>
 </internals>
</jack>

The above patch is in my jack2 (verified the sources).

Starting jackdbus through/with qjackctl.

Is there anything I can test/do/run to provide needed information?

3 seconds of 
[journalctl.log](https://github.com/jackaudio/jack2/files/4615427/journalctl.log)
 attached.

**Comment by kreinhub** [comment]
Hello there! 

I'm getting now the same error while using Jack2 with external soundcard M-Audio-Fast-Track-Pro. Here is the log from Cadence:
```
Sun Oct 25 15:30:19 2020: Starting jack server...
Sun Oct 25 15:30:19 2020: JACK server starting in realtime mode with priority 99
Sun Oct 25 15:30:19 2020: self-connect-mode is "Don't restrict self connect requests"
Sun Oct 25 15:30:19 2020: Acquired audio card Audio1
Sun Oct 25 15:30:19 2020: creating alsa driver ... hw:Pro,0|hw:Pro,1|1024|2|48000|0|0|hwmon|hwmeter|-|32bit
Sun Oct 25 15:30:19 2020: configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
Sun Oct 25 15:30:19 2020: ALSA: final selected sample format for capture: 16bit little-endian
Sun Oct 25 15:30:19 2020: ALSA: use 2 periods for capture
Sun Oct 25 15:30:19 2020: ALSA: final selected sample format for playback: 16bit little-endian
Sun Oct 25 15:30:19 2020: ALSA: use 2 periods for playback
**Sun Oct 25 15:30:19 2020: ERROR: Cannot use real-time scheduling (RR/99) (1: Operation not permitted)**
**Sun Oct 25 15:30:19 2020: ERROR: AcquireSelfRealTime error**
Sun Oct 25 15:30:19 2020: graph reorder: new port 'system:capture_1'
Sun Oct 25 15:30:19 2020: New client 'system' with PID 0
Sun Oct 25 15:30:19 2020: graph reorder: new port 'system:capture_2'
Sun Oct 25 15:30:19 2020: graph reorder: new port 'system:playback_1'
Sun Oct 25 15:30:19 2020: graph reorder: new port 'system:monitor_1'
Sun Oct 25 15:30:19 2020: graph reorder: new port 'system:playback_2'
Sun Oct 25 15:30:19 2020: graph reorder: new port 'system:monitor_2'
Sun Oct 25 15:30:19 2020: New client 'PulseAudio JACK Sink' with PID 1217
Sun Oct 25 15:30:19 2020: Connecting 'PulseAudio JACK Sink:front-left' to 'system:playback_1'
Sun Oct 25 15:30:19 2020: Connecting 'PulseAudio JACK Sink:front-right' to 'system:playback_2'
```
I'm afraid that this issue might cause recording ability on my laptop. Actually this is the main reason why I was starting to research logs and finding solution in network. Also, my audio interface work fine with playback, but seems looks absolutely not working with recording, i.e on Ardour or Reaper. Could you please, check that this MR really fixed this issue? And maybe you can suggest me the solution?

Thanx in advance!

**Comment by imaami** [comment]
@kreinhub I'm not sure your problem is related. You're using the ALSA backend although this issue concerns the PulseAudio backend. But let's see if there's something I can help you with. Could you please tell me:

- What's your JACK version exactly and where is it installed from?
- Did an earlier version of JACK work with the same settings and device? If yes then what was the version?
- Do you have your ulimits configured properly to allow the priority you use?
- Why is your JACK priority set to 99? That's the maximum i.e. way too high. If you were to succeed in starting JACK with rtprio 99 it would likely mess with important system threads.

**Comment by kreinhub** [comment]
@imaami Thanks for the reply!

So... let's see:
1. I installed jack2 from official repositories via pacman. Jack version:
```
$ jackd -V                                                                                                                                                                                                                  
jackdmp version 1.9.16 tmpdir /dev/shm protocol 8
````
2. About settings I think yes, but I didn't try to use them with my external sound card especially for recording. I faced this issue with jack2 already
3. I'm not sure. My limits configuration is below:
```
cat /etc/security/limits.d/99-realtime-privileges.conf                                                                                                                                                                       
@realtime - rtprio 98
@realtime - memlock unlimited

cat /etc/security/limits.conf | tail -n 5                                                                                                                                                                                    
# audio group
@audio		 -	 rtpio		 95
@audio		 - 	 memlock	 unlimited

# End of file
```
AFAIK realtime-privileges.conf  was come with [realtime-privileges](https://www.archlinux.org/packages/?name=realtime-privileges) and /etc/security/limits.conf I got from this article https://wiki.archlinux.org/index.php/Realtime_process_management#Configuring_PAM. 
About realtime-privileges you can read here as well:  https://wiki.archlinux.org/index.php/JACK_Audio_Connection_Kit#Installation
4. Where I can actually check and configure JACK priority?

**Comment by imaami** [comment]
> @imaami Thanks for the reply!

No problem :)

I think you have at least one and possibly two things wrong with your config:

1. The rtprio you're trying to use (99) is actually higher than your configured maximum (98). This alone will prevent JACK from gaining realtime scheduling even if everything else is OK.

2. You might not have yet added your user to the realtime group, or if you have you might have not done the necessary logout and login needed to activate the setting.

Being a Debian user myself I had to take a look at how Arch handles these things. So if I've understood correctly you've installed the realtime-privileges package, which is good. Just a few things and you should be all set:

> My limits configuration is below:
> 
>     cat /etc/security/limits.d/99-realtime-privileges.conf
>     @realtime - rtprio 98
>     @realtime - memlock unlimited

OK, so you'll be using a group called realtime to gain realtime privileges. That means this stuff below isn't actually used:

>     cat /etc/security/limits.conf | tail -n 5
>     # audio group
>     @audio		 -	 rtpio		 95
>     @audio		 - 	 memlock	 unlimited
>     
>     # End of file

Just remove the lines you copypasted to /etc/security/limits.conf.

> 4. Where I can actually check and configure JACK priority?

Cadence should have a JACK settings dialog where you'll find the realtime priority setting in the "Engine" tab: https://kx.studio/Applications:Cadence-JackSettings. Set it to something like 80.

And then the important part: your user needs to actually be in the realtime group. If you haven't done so already you can do it with `useradd -aG realtime <yourusername>`. Afterwards you need to re-login (or just reboot, whatever).

**Comment by kreinhub** [comment]
Thank for suggestions =)

Of course my user in realtime group already:
```
$ groups                                                                                                                                                                                                                       
realtime docker users audio wheel adm
```
Also, I comment that stuff in cat /etc/security/limits.conf, change priority value in Cadence settings to 80 and reboot after it, but unfortunately it didn't help. 

I guess, that maybe I even didn't do something in my settings in Reaper or Cadence. Earlier I was working with sound production on Windows platform =) Or perhaps it's a bug and I should try to switch to Pulse Audio for example

Here is my Cadence connections map https://i.imgur.com/kF3nsYy.png and settings https://i.imgur.com/mVbeBWR.png
Reaper device https://i.imgur.com/jIJQUEZ.png and track https://i.imgur.com/2iXHnzQ.png settings

Do they look right? =) Sorry for those questions

P.S. There is a big topic about similar issue with M-Audio Fast Track Pro and Cadence settings I've got from there https://linuxmusicians.com/viewtopic.php?t=11016

**Pull request merged**
