### PR TITLE
Netjack dev: Squashed Interface selection plus IPv6

### PR DESCRIPTION
**Pull request by rufferson**
Hi,
Here's a new branch with rebased and squashed patches.
I've run some tests and ubuntu debs are available at https://launchpad.net/~rufferson/+archive/snd for further testing.
No windows support, mac should be ok since I've followed precisely POSIX's IEEE Std 1003.1, 2004 Edition.
Commits contain more descriptive logs.
Regards,
Ruslan

### CODE REVIEW

**Comment by adiknoth** [comment]
I know it's been four years, but do you still care about this pull request? If so, please rebase/update, and I promise to take a timely look.

Thanks for contributing, our lack of responsiveness is truly a shame. My sincerest apologies.

**Comment by rufferson** [comment]
Hi Adrian,

Long time indeed, let me take a look. 
Conflict report is looking promising but as far as I remember from the mailgroup there were some substantial changes in the network stack at some point (byte alignment or endiannes). So would need to carefully check and test.

Regards,
Ruslan

**Comment by rufferson** [comment]
Well, it appeared to be in the end better than I thought.
```
ruff@boo:~/co/jack2$ uname -a
Linux boo.ruff.mobi 4.4.51-627f0117679bc72ef5e58881035f567a-3 #1 SMP Fri Mar 3 08:15:02 CET 2017 armv7l armv7l armv7l GNU/Linux
ruff@boo:~/co/jack2$ LD_LIBRARY_PATH=/opt/jack/lib /opt/jack/bin/jackd -v -d net -a ff05::193a
jackdmp 1.9.11
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Cannot lock down 82287136 byte memory area (Cannot allocate memory)
Jack: JackPosixThread::StartImp : create non RT thread
Jack: JackPosixThread::ThreadHandler : start
Jack: JackNetUnixSocket::ProbeAF trying AF[10], TYPE[2], PROTO[17]
Jack: JackNetUnixSocket::ProbeAF probed[3] AF[10] for ff05::193a
Jack: JackNetDriver::JackNetDriver ip ff05::193a, port 19000
... snip ...
Initializing connection with trx.ruff.mobi...
Jack: JackNetSlaveInterface::SendStartToMaster
Jack: JackNetSlaveInterface::SetParams audio in = 2 audio out = 2 MIDI in = 0 MIDI out = 0
Jack: audio_size 12000.000000
Jack: midi_size 0.000000
Jack: SetNetBufferSize bufsize = 405000
... snip ...
**************** Network parameters ****************
Name : boo.ruff.mobi
Protocol revision : 8
MTU : 1500
Master name : trx.ruff.mobi
Slave name : boo.ruff.mobi
ID : 1
Transport Sync : no
Send channels (audio - midi) : 2 - 0
Return channels (audio - midi) : 2 - 0
Sample rate : 48000 frames per second
Period size : 1024 frames per period
Network latency : 5 cycles
SampleEncoder : Float
Slave mode : async   
****************************************************
```
And from the other side
```
[ruff@trx wocky]$ uname -a
Linux trx.ruff.mobi 4.10.1-1-ARCH #1 SMP PREEMPT Sun Feb 26 21:08:53 UTC 2017 x86_64 GNU/Linux
[ruff@trx wocky]$ jack_load netmanager -i '-a ff05::193a'
... from the jackdbus.log ...
Thu Mar 16 22:00:50 2017: Starting Jack NetManager
Thu Mar 16 22:00:50 2017: Jack: JackRequest::Notification
Thu Mar 16 22:00:50 2017: Listening on 'ff05::193a:19000%any'
Thu Mar 16 22:00:50 2017: Jack: JackNetMasterManager::Run
Thu Mar 16 22:00:50 2017: Jack: JackDriver::ClientNotify ref = 1 driver = freewheel name = freewheel notify = 18
Thu Mar 16 22:00:50 2017: Jack: JackClient::ClientNotify ref = 4 name = netmanager notify = 18
Thu Mar 16 22:00:50 2017: Jack: JackNetUnixSocket::ProbeAF trying AF[10], TYPE[2], PROTO[17]
Thu Mar 16 22:00:50 2017: Jack: JackDriver::ClientNotify ref = 1 driver = freewheel name = freewheel notify = 18
Thu Mar 16 22:00:50 2017: Jack: JackDriver::ClientNotify ref = 1 driver = freewheel name = freewheel notify = 18
Thu Mar 16 22:00:50 2017: Jack: JackClient::ClientNotify ref = 4 name = netmanager notify = 18
Thu Mar 16 22:00:50 2017: Jack: JackNetUnixSocket::ProbeAF probed[15] AF[10] for ff05::193a
...snip...
Thu Mar 16 22:00:51 2017: Jack: JackNetMasterManager::InitMaster slave : boo.ruff.mobi
Thu Mar 16 22:00:51 2017: Takes physical 2 audio input(s) for slave
Thu Mar 16 22:00:51 2017: Takes physical 2 audio output(s) for slave
Thu Mar 16 22:00:51 2017: Takes physical 0 MIDI input(s) for slave
Thu Mar 16 22:00:51 2017: Takes physical 0 MIDI output(s) for slave
Thu Mar 16 22:00:51 2017: Jack: JackNetMaster::JackNetMaster
Thu Mar 16 22:00:51 2017: Jack: JackNetMasterInterface::Init : ID 1
Thu Mar 16 22:00:51 2017: Jack: JackNetUnixSocket::SetTimeout 10000000 usecs
Thu Mar 16 22:00:51 2017: Sending parameters to boo.ruff.mobi...
Thu Mar 16 22:00:51 2017: Jack: JackNetMasterInterface::SetParams audio in = 2 audio out = 2 MIDI in = 0 MIDI out = 0
Thu Mar 16 22:00:51 2017: Jack: audio_size 12000.000000
Thu Mar 16 22:00:51 2017: Jack: midi_size 0.000000
Thu Mar 16 22:00:51 2017: Jack: SetNetBufferSize bufsize = 405000
Thu Mar 16 22:00:51 2017: Jack: jack_client_open boo.ruff.mobi
Thu Mar 16 22:00:51 2017: Jack: JackInternalClient::Open name = boo.ruff.mobi
Thu Mar 16 22:00:51 2017: Jack: Check protocol client = 8 server = 8
Thu Mar 16 22:00:51 2017: Jack: JackEngine::ClientInternalOpen: name = boo.ruff.mobi
Thu Mar 16 22:00:51 2017: Jack: JackEngine::AllocateRefNum ref = 3
Thu Mar 16 22:00:51 2017: Jack: JackLinuxFutex::Allocate name = jack_sem.1000_default_boo.ruff.mobi val = 0
Thu Mar 16 22:00:51 2017: Jack: JackPosixProcessSync::TimedWait time out = 5000000
Thu Mar 16 22:00:51 2017: Jack: JackPosixProcessSync::TimedWait finished delta = 4639.0
Thu Mar 16 22:00:51 2017: Jack: JackEngine::NotifyAddClient: name = boo.ruff.mobi
Thu Mar 16 22:00:51 2017: Jack: JackDriver::ClientNotify ref = 3 driver = system name = boo.ruff.mobi notify = 0
Thu Mar 16 22:00:51 2017: Jack: JackClient::ClientNotify ref = 0 name = system notify = 0
Thu Mar 16 22:00:51 2017: Jack: JackDriver::ClientNotify ref = 3 driver = freewheel name = boo.ruff.mobi notify = 0
Thu Mar 16 22:00:51 2017: Jack: JackClient::ClientNotify ref = 1 name = freewheel notify = 0
Thu Mar 16 22:00:51 2017: Jack: JackClient::ClientNotify ref = 3 name = boo.ruff.mobi notify = 0
Thu Mar 16 22:00:51 2017: Jack: JackClient::kAddClient fName = dbusapi name = boo.ruff.mobi
Thu Mar 16 22:00:51 2017: Jack: client 'boo.ruff.mobi' created
Thu Mar 16 22:00:51 2017: New client 'boo.ruff.mobi' with PID 0
...snip...
Thu Mar 16 22:00:51 2017: New NetMaster started
Thu Mar 16 22:00:51 2017: **************** Network parameters ****************
Thu Mar 16 22:00:51 2017: Name : boo.ruff.mobi
Thu Mar 16 22:00:51 2017: Protocol revision : 8
Thu Mar 16 22:00:51 2017: MTU : 1500
Thu Mar 16 22:00:51 2017: Master name : trx.ruff.mobi
Thu Mar 16 22:00:51 2017: Slave name : boo.ruff.mobi
Thu Mar 16 22:00:51 2017: ID : 1
Thu Mar 16 22:00:51 2017: Transport Sync : no
Thu Mar 16 22:00:51 2017: Send channels (audio - midi) : 2 - 0
Thu Mar 16 22:00:51 2017: Return channels (audio - midi) : 2 - 0
Thu Mar 16 22:00:51 2017: Sample rate : 48000 frames per second
Thu Mar 16 22:00:51 2017: Period size : 1024 frames per period
Thu Mar 16 22:00:51 2017: Network latency : 5 cycles
Thu Mar 16 22:00:51 2017: SampleEncoder : Float
Thu Mar 16 22:00:51 2017: Slave mode : async
Thu Mar 16 22:00:51 2017: ****************************************************
```

Unfortunately I've disassembled my daw setup so I cannot test it fully (i've used a docker on my router to simulate a slave) but devices with different arch connected and synced. Maybe later I'll recover some old gears and connect them all together.

**Comment by 7890** [comment]
See https://github.com/jackaudio/jack2/pull/427

**Comment by 7890** [comment]
Consolidated PR is here: https://github.com/jackaudio/jack2/pull/427

**Pull request closed without merging**
