### PR TITLE
Fix wscripts syntax

### PR DESCRIPTION
**Pull request by dvzrv**
This fixes the Python syntax in all wscripts (excluding man/wscript, as it is fixed by #825). The fixes include:

* all wscripts are allowed a line length of 120 chars
* unused imports are removed
* moves file-wide imports to top of file
* general syntax fixes according to flake8 recommendations
* adds a flake8 configuration file and runs flake8 against all wscripts in CI
* allows for the IIO driver to be built (picks up source files correctly)

This allows for better readability and detection of errors. Running flake8 can be included in CI as well.

### CODE REVIEW

**Comment by falkTX** [comment]
Please rebase against latest develop branch, so we can test the windows builds that have now been fixed.
Thanks

**Comment by falkTX** [comment]
The Ubuntu build fails because of a "VERSION=" parsing error that is now changed, I guess it just need to be replaced with "VERSION = ".

**Comment by dvzrv** [comment]
> The Ubuntu build fails because of a "VERSION=" parsing error that is now changed, I guess it just need to be replaced with "VERSION = ".

That extraction is also very brittle (I also tried using sed on the file, but somehow this didn't work in CI...).
We could think about  moving the version information into a simple .env type file, where only `key=value` pairs are defined (without any quotes).
Aside from being less painful to parse (and set), as another side effect it would allow other build systems to make use of it in the future, while still only having to update one file to set the version strings :)

**Comment by dvzrv** [comment]
> Please rebase against latest develop branch, so we can test the windows builds that have now been fixed. Thanks

Seems to work! \o/

**Comment by dvzrv** [comment]
If CI passes, this is good to go!

**Pull request merged**
