### PR TITLE
IEEE 1722 AVTP Media Clock Backend

### PR DESCRIPTION
**Pull request by chris-kuhr**
Code for the paper presented at LAC 19.

### CODE REVIEW

**Comment by falkTX** [comment]
While the proposal for this is quite nice, this PR is quite awful...

Please bring it up to date to latest jack2 code, and target the develop branch.
I really can't merge this, or even begin to review it.

**Comment by chris-kuhr** [comment]
"this PR is quite awful..." is not helpful.

jack2coding style sais: 
"- Contributions to existing files must follow the coding style already used in them.
- Different coding style is acceptable for new files.
- Both C++ and plain C contributions are accepted.
 "

These are met. so I have no idea what your complaint is about. please be more  specific.

**Comment by falkTX** [comment]
There are 282 files changed, and reverting of changes that were pushed into master.

Look at the diff generated by the PR:
https://patch-diff.githubusercontent.com/raw/jackaudio/jack2/pull/450.patch

Just quickly looking at it I see many issues:
1. There are 52k lines, so impossible to review properly
2. There are commits there related to waf (entire folder has changed)
3. Example clients code were changed, random stuff removed or commented out
4. New code added that is a simple copy&paste of existing one, just renamed (like simple_client1.c)

This is one of the uncleanliest PRs I ever saw really.
Please fix it and try again.
Thank you

**Comment by chris-kuhr** [comment]
Ok, thank you. This is information I can use. At the end, my changes are only one additional folder in the linux subdirectory, .gitsubmodule and the wsscript. I did not modify any other existing files.

Seems I merged with a wrong branch.

**Comment by 7890** [comment]
@chris-kuhr out of curiosity, do you run an instance of jack with this patch synced to an AVTP network?

**Comment by chris-kuhr** [comment]
yes

**Comment by 7890** [comment]
I just want to say this is pretty cool. I haven't any such devices but sounds like a useful new backend!

**Comment by chris-kuhr** [comment]
I would be glad if this work could be of use for more people then just our research project!

**Comment by 7890** [comment]
Thinking a step further, if this gets merged we need you to maintain it for at least the next 5 years :)

**Comment by chris-kuhr** [comment]
that won't be much of a problem.  It took me 5 five to have something useful with AVB working... ;-)

**Comment by ahellquist** [comment]
I for one is super **interested** in the possible AVB additions to Jack and would like to thank you very much.
It seem something odd is going on with your PR but don't feel discouraged. I am certain a lot of people is exited.

**Comment by 7890** [comment]
Follow-up PR is https://github.com/jackaudio/jack2/pull/452

**Pull request closed without merging**
