### PR TITLE
Use dllimport/dllexport in public jack headers

### PR DESCRIPTION
**Pull request by amurzeau**
I've finally come-up with a maybe more "radical" solution.

CFLAGS and CXXFLAGS are modified to add a global `BUILDING_JACK` define that choose between dllexport and dllimport.

When building jack, symbols are declared using dllexport.
When headers are used by an application, symbols will be declared using dllimport.

Fixes: #792

### CODE REVIEW

**Comment by amurzeau** [comment]
I've tried to compile qjackctl against that version of Jack (from CI) and it worked fine.
Also, running qjackctl (compiled with MSVC) with that Jack version is working too (after minor changes to qjackctl which was using `free` instead of `jack_free`).

The qjackctl compiled with MSVC is also working fine with official versions of Jack.

**Comment by falkTX** [comment]
Glad that you found something that works, but BUILDING_JACK macro is not needed.
As I said on the other ticket, the common/jack/* headers are not used when building jack2, so this definition makes nothing. you can set BUILDING_JACK to always be dllimport, it should build and work just the same

**Comment by falkTX** [comment]
I meant to say JACK_CLIENT_API_EXPORT as dllimport

**Comment by amurzeau** [comment]
I've tried that, but it failed the build: https://github.com/amurzeau/jack2/actions/runs/1152225544
In this build, I've set an equivalent of BUILDING_JACK only for clientlib and serverlib, but the build failed at jacknet as I said here: https://github.com/jackaudio/jack2/issues/792#issuecomment-902994461

**Comment by falkTX** [comment]
hmm so maybe it is just the ring buffer that needs some attention.
you should be able to define the ringbuffer functions instead of including common/jack/ringbuffer.h, the same way that the code sets up the rest of the API calls to export.

**Comment by amurzeau** [comment]
When greping for includes of jack, I find several occurrences (I've removed occurrences from common/jack, tools, tests and example clients).
I will try to see if it is sufficient. Only jacknet seems impacted, dbus is probably never compiled on Windows.

```bash
./common/JackMetadata.h:#include <jack/uuid.h>
./common/JackWeakAPI.c:#include <jack/jack.h>
./common/JackWeakAPI.c:#include <jack/session.h>
./common/JackWeakAPI.c:#include <jack/thread.h>
./common/JackWeakAPI.c:#include <jack/midiport.h>
./common/netjack.c:#include <jack/types.h>
./common/netjack.c:#include "jack/jslist.h"
./common/netjack.h:#include <jack/types.h>
./common/netjack.h:#include <jack/jack.h>
./common/netjack.h:#include <jack/transport.h>
./common/netjack.h:#include "jack/jslist.h"
./common/netjack_packet.c:#include <jack/types.h>
./common/netjack_packet.h:#include <jack/jack.h>
./common/netjack_packet.h:#include <jack/types.h>
./common/netjack_packet.h:#include <jack/jslist.h>
./common/netjack_packet.h:#include <jack/midiport.h>
./dbus/audio_reserve.c:#include "jack/control.h"
./dbus/controller_iface_session_manager.c:#include "jack/session.h"
./dbus/controller_iface_session_manager.c:#include "jack/control.h"
./dbus/controller_internal.h:#include "jack/control.h"
./dbus/controller_internal.h:#include "jack/jack.h"
./dbus/controller_internal.h:#include "jack/session.h"
./dbus/jackdbus.c:#include "jack/jack.h"
./dbus/jackdbus.c:#include "jack/jslist.h"
./dbus/jackdbus.c:#include "jack/control.h"
./dbus/params.h:#include "jack/control.h"
./dbus/reserve.c:#include "jack/control.h"
./dbus/sigsegv.c:#include "jack/control.h"
./dbus/xml_nop.c:#include <jack/driver.h>
./dbus/xml_nop.c:#include <jack/engine.h>
./linux/alsa/alsa_midi_impl.h:#include <jack/messagebuffer.h>
./linux/firewire/ffado_driver.h://#include <jack/midiport.h>
```

**Comment by amurzeau** [comment]
I've tried to fix ringbuffer, but clientlib use jack/uuid.h header: https://github.com/amurzeau/jack2/runs/3387122466?check_suite_focus=true

**Comment by amurzeau** [comment]
Closing as I'm not putting more effort on it, and using MinGW is a solution.
I still think that using macros is the way to go to avoid too much code change, if someday this is pushed again.

**Pull request closed without merging**
